import requests
import threading
import time
from datetime import datetime
from app.config import TELEGRAM_BOT_TOKEN, TELEGRAM_CHAT_ID, IS_TELEGRAM_CONFIGURED
from app.models import global_state, ChatMessage, AlertNotification
from app.agents.diagnostics import DiagnosticsAgent

class TelegramBotService:
    _poll_thread = None
    _stop_polling = False

    @staticmethod
    def send_alert(message: str) -> bool:
        timestamp = datetime.now().strftime("%I:%M:%S %p")
        
        # 1. Log to state chat history and alert notifications (always, for mock simulation and display)
        new_alert = AlertNotification(
            type="Telegram",
            subject="Hardware Status Alert",
            body=message,
            timestamp=timestamp
        )
        global_state.alerts_history.insert(0, new_alert)
        
        # Also post in chatbot window
        global_state.chat_history.append(ChatMessage(
            sender="System",
            message=f"🔔 TELEGRAM ALERT: {message}",
            timestamp=datetime.now().strftime("%I:%M %p")
        ))
        
        print(f"[Telegram Alert Logged]: {message}")

        # 2. If Token and Chat ID are configured, send real message
        if IS_TELEGRAM_CONFIGURED and TELEGRAM_CHAT_ID:
            try:
                url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage"
                payload = {
                    "chat_id": TELEGRAM_CHAT_ID,
                    "text": f"🌿 *Zentra Flora Alert* 🌿\n\n{message}",
                    "parse_mode": "Markdown"
                }
                r = requests.post(url, json=payload, timeout=5)
                if r.status_code == 200:
                    print("[Real Telegram Alert Dispatched Successfully]")
                    return True
                else:
                    print(f"[Real Telegram Alert Failed Code]: {r.status_code} - {r.text}")
                    return False
            except Exception as e:
                print(f"[Real Telegram Alert Error]: {str(e)}")
                return False
        else:
            print("[Telegram not configured in .env - Running in Simulation Mode]")
            return True

    @staticmethod
    def process_incoming_message(text: str) -> str:
        """Process incoming chat query and return a responsive statement."""
        cmd = text.strip().lower()
        
        if cmd == "/start" or "hello" in cmd or "hi" in cmd:
            return (
                "Welcome to Zentra Flora Greenhouse Assistant! 🌿\n\n"
                "I am your automated plant guardian. You can use these commands:\n"
                "• `/status` - Current greenhouse temperature, humidity, and sensors.\n"
                "• `/tasks` - Fetch daily chores generated by the AI Scheduler.\n"
                "• `/pump_on` or `/pump_off` - Control active watering pump.\n"
                "• `/fan_on` or `/fan_off` - Control exhaust ventilation fan.\n"
                "• Or type 'diagnose leaf [filename]' to simulate diagnostics."
            )
            
        elif cmd == "/status" or "status" in cmd:
            s = global_state.sensors
            a = global_state.actuators
            t = global_state.targets
            p = global_state.current_plant
            stage = global_state.growth_stage
            
            pump_emoji = "🟢 ON" if a.pump else "🔴 OFF"
            fan_emoji = "🟢 ON" if a.fan else "🔴 OFF"
            lights_emoji = "🟢 ON" if a.grow_lights else "🔴 OFF"
            
            # Simple bounds check representation
            health = "Exemplary ❇️"
            if s.soil_moisture < t.min_soil_moisture or s.temperature > t.max_temp:
                health = "Needs Attention ⚠️"
                
            return (
                f"📊 *Current Greenhouse Status* ({p} - {stage})\n\n"
                f"🌡️ Temp: {s.temperature}°C (Ideal: {t.min_temp}-{t.max_temp}°C)\n"
                f"💧 Humidity: {s.humidity}% (Ideal: {t.min_humidity}-{t.max_humidity}%)\n"
                f"☀️ Ambient Light: {s.light} Lux (Ideal: {t.min_light}-{t.max_light} Lux)\n"
                f"🪵 Soil Moisture: {s.soil_moisture}% (Ideal: {t.min_soil_moisture}-{t.max_soil_moisture}%)\n\n"
                f"⚙️ *Actuators Status*:\n"
                f"💧 Water Pump: {pump_emoji}\n"
                f"💨 Ventilation Fan: {fan_emoji}\n"
                f"💡 Grow Lights: {lights_emoji}\n\n"
                f"🏥 Greenhouse Health: {health}"
            )
            
        elif cmd == "/tasks" or "task" in cmd:
            from app.agents.scheduler import TaskSchedulerAgent
            tasks = TaskSchedulerAgent.generate_daily_tasks(
                global_state.current_plant,
                global_state.growth_stage,
                global_state.age_days
            )
            
            task_lines = []
            for idx, task in enumerate(tasks, 1):
                box = "✅" if task["completed"] else "🔳"
                task_lines.append(f"{idx}. {box} *[{task['category']}]* {task['task']} ({task['priority']})")
                
            return "📋 *Agri-Todo Chores Checklist*:\n\n" + "\n".join(task_lines)
            
        elif cmd == "/pump_on":
            global_state.actuators.pump = True
            return "💧 Water Pump turned ON manually. Greenhouse soil is being irrigated."
            
        elif cmd == "/pump_off":
            global_state.actuators.pump = False
            return "💧 Water Pump turned OFF manually."
            
        elif cmd == "/fan_on":
            global_state.actuators.fan = True
            return "💨 Ventilation Fan turned ON manually. Commencing cooling airflow."
            
        elif cmd == "/fan_off":
            global_state.actuators.fan = False
            return "💨 Ventilation Fan turned OFF manually."
            
        elif "diagnose" in cmd or "leaf" in cmd or "photo" in cmd:
            # Simulated leaf diagnose keyword matching
            fname = "diseased_leaf.png"
            if "mite" in cmd:
                fname = "spider_mites_infestation.jpg"
            elif "mildew" in cmd:
                fname = "powdery_mildew_spots.png"
            elif "spot" in cmd:
                fname = "leaf_spot_fungus.jpeg"
            elif "healthy" in cmd:
                fname = "healthy_green_foliage.png"
                
            diag = DiagnosticsAgent.analyze_leaf_photo(fname, 512000)
            
            return (
                f"🏥 *AI Diagnostics Agent Report* 🏥\n\n"
                f"📄 Filename: {diag['filename']}\n"
                f"🔬 Diagnosis: *{diag['diagnosis']}*\n"
                f"📊 Confidence: {diag['confidence']}%\n"
                f"🌡️ Severity: {diag['severity']}\n\n"
                f"📝 *Symptoms*:\n{diag['symptoms']}\n\n"
                f"🚨 *Urgent Action*:\n{diag['urgent_action']}\n\n"
                f"🌱 *Organic Cure*:\n{diag['organic_treatment']}"
            )
            
        else:
            return (
                "Sorry, I did not understand that command. 🧐\n"
                "Try writing `/status` or `/tasks` for actionable data."
            )

    @classmethod
    def start_polling(cls):
        """Starts real polling thread if token is present, else do nothing."""
        if not IS_TELEGRAM_CONFIGURED:
            print("[Telegram polling bot skipped - running in simulation-only mode]")
            return
            
        if cls._poll_thread is not None and cls._poll_thread.is_alive():
            print("[Telegram polling bot already active]")
            return

        cls._stop_polling = False
        cls._poll_thread = threading.Thread(target=cls._polling_loop, daemon=True)
        cls._poll_thread.start()
        print("[Telegram Real Polling Daemon Started]")

    @classmethod
    def stop_polling(cls):
        cls._stop_polling = True
        if cls._poll_thread:
            cls._poll_thread.join(timeout=2)
            print("[Telegram Real Polling Daemon Terminated]")

    @classmethod
    def _polling_loop(cls):
        offset = 0
        url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/getUpdates"
        
        while not cls._stop_polling:
            try:
                # Poll with long polling timeout
                params = {"offset": offset, "timeout": 5}
                r = requests.get(url, params=params, timeout=10)
                if r.status_code == 200:
                    data = r.json()
                    for update in data.get("result", []):
                        offset = update["update_id"] + 1
                        message = update.get("message", {})
                        chat = message.get("chat", {})
                        chat_id = chat.get("id")
                        text = message.get("text", "")
                        
                        if not text or not chat_id:
                            continue
                            
                        # Standardize name
                        from_user = message.get("from", {})
                        username = from_user.get("first_name", "User")
                        
                        # Add user message to dashboard chat
                        timestamp = datetime.now().strftime("%I:%M %p")
                        global_state.chat_history.append(ChatMessage(
                            sender="User",
                            message=text,
                            timestamp=timestamp
                        ))
                        
                        # Process response
                        reply = cls.process_incoming_message(text)
                        
                        # Append bot response to dashboard chat
                        global_state.chat_history.append(ChatMessage(
                            sender="Bot",
                            message=reply,
                            timestamp=timestamp
                        ))
                        
                        # Send reply to actual Telegram chat
                        send_url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage"
                        requests.post(send_url, json={
                            "chat_id": chat_id,
                            "text": reply,
                            "parse_mode": "Markdown"
                        }, timeout=5)
            except Exception as e:
                print(f"[Telegram Polling Loop Error]: {str(e)}")
                time.sleep(5)
            time.sleep(1)
stream = None
